export { default as Header } from './header/Header'
export { default as Home } from './home/Home'
export { default as Footer } from './footer/Footer'
export { default as Contact } from './contact/Contact'
export { default as About } from './about/About'
export { default as Application } from './applications/Aplications'
